import { Product } from "./types";

export const productData: Product[] = [
  {
    id: 1,
    name: "Smart 4K Ultra HD TV",
    price: 799.99,
    category: "Electronics",
    rating: 4.8,
    image: "/images/products/smart-tv.jpg",
    inStock: true,
    description: "4K Ultra HD Smart TV with HDR and built-in streaming",
    brand: "TechVision",
    discount: 15,
    tags: ["featured", "bestseller"],
    colors: ["black", "silver"]
  },
  {
    id: 2,
    name: "Advanced Fitness Tracker",
    price: 99.99,
    category: "Wearables",
    rating: 4.7,
    image: "/images/products/fitness-tracker.jpg",
    inStock: true,
    description: "Advanced fitness tracking with heart rate monitoring",
    brand: "FitTech",
    discount: 0,
    tags: ["new"],
    colors: ["black", "blue", "red"]
  },
  {
    id: 3,
    name: "Professional Mirrorless Camera",
    price: 1249.99,
    category: "Photography",
    rating: 4.9,
    image: "/images/products/camera.jpg",
    inStock: false,
    description: "Professional mirrorless camera with 4K video",
    brand: "PhotoPro",
    discount: 8,
    tags: ["premium"],
    colors: ["black"]
  },
  {
    id: 4,
    name: "Noise Cancelling Headphones",
    price: 249.99,
    category: "Audio",
    rating: 4.6,
    image: "/images/products/headphones.jpg",
    inStock: true,
    description: "Premium wireless headphones with noise cancellation",
    brand: "SoundMaster",
    discount: 20,
    tags: ["bestseller", "featured"],
    colors: ["black", "white", "blue"]
  },
  {
    id: 5,
    name: "Ultra-thin Laptop",
    price: 1299.99,
    category: "Computers",
    rating: 4.7,
    image: "/images/products/laptop.jpg",
    inStock: true,
    description: "Powerful ultra-thin laptop with all-day battery life",
    brand: "TechBook",
    discount: 10,
    tags: ["premium", "featured"],
    colors: ["silver", "space gray"]
  },
  {
    id: 6,
    name: "Wireless Gaming Mouse",
    price: 79.99,
    category: "Gaming",
    rating: 4.5,
    image: "/images/products/gaming-mouse.jpg",
    inStock: true,
    description: "High-precision wireless gaming mouse with customizable RGB",
    brand: "GameTech",
    discount: 0,
    tags: ["gaming"],
    colors: ["black", "white"]
  },
  {
    id: 7,
    name: "Smart Home Speaker",
    price: 129.99,
    category: "Smart Home",
    rating: 4.4,
    image: "/images/products/smart-speaker.jpg",
    inStock: true,
    description: "Voice-controlled smart speaker with premium sound",
    brand: "EchoTech",
    discount: 15,
    tags: ["smart-home"],
    colors: ["black", "white", "gray"]
  },
  {
    id: 8,
    name: "Smartphone Pro Max",
    price: 999.99,
    category: "Electronics",
    rating: 4.8,
    image: "/images/products/smartphone.jpg",
    inStock: true,
    description: "Latest flagship smartphone with advanced camera system",
    brand: "MobiTech",
    discount: 5,
    tags: ["premium", "bestseller"],
    colors: ["midnight", "silver", "gold", "blue"]
  },
  {
    id: 9,
    name: "Wireless Earbuds",
    price: 149.99,
    category: "Audio",
    rating: 4.6,
    image: "/images/products/earbuds.jpg",
    inStock: true,
    description: "True wireless earbuds with active noise cancellation",
    brand: "SoundMaster",
    discount: 0,
    tags: ["new"],
    colors: ["black", "white"]
  },
  {
    id: 10,
    name: "Gaming Console",
    price: 499.99,
    category: "Gaming",
    rating: 4.9,
    image: "/images/products/gaming-console.jpg",
    inStock: false,
    description: "Next-gen gaming console with 4K gaming and ray tracing",
    brand: "GameStation",
    discount: 0,
    tags: ["premium", "gaming"],
    colors: ["black"]
  },
  {
    id: 11,
    name: "Smart Watch Series 5",
    price: 349.99,
    category: "Wearables",
    rating: 4.7,
    image: "/images/products/smartwatch.jpg",
    inStock: true,
    description: "Advanced smartwatch with health monitoring and GPS",
    brand: "FitTech",
    discount: 12,
    tags: ["featured"],
    colors: ["black", "silver", "gold"]
  },
  {
    id: 12,
    name: "Portable SSD 1TB",
    price: 179.99,
    category: "Storage",
    rating: 4.8,
    image: "/images/products/ssd.jpg",
    inStock: true,
    description: "Ultra-fast portable SSD with 1TB storage",
    brand: "DataStore",
    discount: 0,
    tags: ["new"],
    colors: ["black"]
  }
];